# Generated by Django 2.1.7 on 2019-03-07 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FillInBlank',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='study.Question')),
                ('answer', models.TextField(max_length=100)),
            ],
            bases=('study.question',),
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='study.Question')),
                ('choices', models.TextField()),
                ('answer', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
            bases=('study.question',),
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='study.Question')),
                ('answer', models.TextField()),
            ],
            bases=('study.question',),
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='study.Question')),
                ('choices', models.TextField()),
                ('answer', models.IntegerField()),
            ],
            bases=('study.question',),
        ),
        migrations.CreateModel(
            name='TrueOrFalse',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='study.Question')),
                ('answer', models.BooleanField()),
            ],
            bases=('study.question',),
        ),
    ]
